---
- name: Deploy Java Application to Tomcat
  hosts: tomcat-server
  become: yes  # Use sudo to execute tasks

  tasks:
    - name: Copy WAR File
      copy:
        src: /var/lib/jenkins/workspace/CICDAnsible/target/LoginWebApp-1.war
        dest: /opt/apache-tomcat-9.0.80/webapps/LoginWebApp-1.war
      notify: Restart Tomcat

  handlers:
    - name: Restart Tomcat
      systemd:
        name: tomcat  # Modify to match your actual service name
        state: restarted

